---
title: "RWorksheet#5_group(freires,rocillo,sanico)"
output: pdf_document
date: "2024-11-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Extracting TV Shows Reviews

1. Each group needs to extract the top 50 tv shows in Imdb.com. It will include the rank, the title of the
tv show, tv rating, the number of people who voted, the number of episodes, the year it was released.
It will also include the number of user reviews and the number of critic reviews, as well as the popularity
rating for each tv shows.

```{r}
library(rvest)  
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

url <- 'https://www.imdb.com/chart/toptv/?ref_=nv_tvv_250'

session <- bow(url,
               user_agent = "Educational")
session
```

```{r}
library(rvest)
library(dplyr)

title <- read_html(url) %>%
  html_nodes('h3.ipc-title__text') %>% 
  html_text


data_ <- data.frame(
    titleDf = title[1:25])

data_
```

```{r}
title_rank <- as.data.frame(data_, stringsAsFactors = FALSE)
colnames(title_rank) <- "rank"

split_df <- strsplit(as.character(title_rank$rank), "\\.", fixed = FALSE)
split_df <- data.frame(do.call(rbind, split_df), stringsAsFactors = FALSE)
colnames(split_df) <- c("rank", "title")

split_df <- split_df %>% select(rank, title)

split_df$title <- trimws(split_df$title)

title_rank <- split_df
title_rank
```

```{r}
rating <- read_html(url) %>%
  html_nodes('.ipc-rating-star--rating') %>%
  html_text()

rating_ <- data.frame(
    ratingDf = rating[2:25])

rating_
```

```{r}
voted <- read_html(url) %>%
  html_nodes('.ipc-rating-star--voteCount') %>%
  html_text()
  vot <- gsub('[()]', '', voted)
  
  voted_ <- data.frame(
    votedDf = voted[2:25])

voted_
```

```{r}

episodes <- read_html(url) %>%
  html_nodes("span.sc-300a8231-7.eaXxft.cli-title-metadata-item:nth-of-type(2)") %>%
  html_text()
  

episodes_ <- data.frame(
    episodesDf = episodes[1:25])

episodes_
```

```{r}
years <- read_html(url) %>%
  html_nodes('span.sc-300a8231-7.eaXxft.cli-title-metadata-item:nth-of-type(1)') %>%
  html_text()

years_ <- data.frame(
    years_releases = years[1:25])

years_

```

```{r}
tv_shows <- data.frame(
  Rank = title_rank[,1],
  Title = title_rank[,2],
  Rating = rating,
  Voters = voted,
  Episodes = episodes,
  Year = years
)
tv_shows
```

```{r}
home_link <- 'https://www.imdb.com/chart/toptv/'
main_page <- read_html(home_link)

links <- main_page %>%
  html_nodes("a.ipc-title-link-wrapper") %>%
  html_attr("href")

show_url_df <- do.call(rbind, lapply(links, function(link) {
  complete_link <- paste0("https://imdb.com", link)

 usrv_link <- read_html(complete_link)
  usrv_link_page <- usrv_link %>%
    html_nodes('a.isReview') %>%
    html_attr("href")
  
   critic <- usrv_link %>%
              html_nodes("span.score") %>%
              html_text()
  critic_df <- data.frame(Critic_Reviews = critic[2], stringsAsFactors = FALSE)
  
 pop_rating <- usrv_link %>%
              html_nodes('[data-testid="hero-rating-bar__popularity__score"]') %>%
              html_text()
  
   usrv <- read_html(paste0("https://imdb.com", usrv_link_page[1]))
  usrv_count <- usrv %>%
    html_nodes('[data-testid="tturv-total-reviews"]') %>%
    html_text()

 return(data.frame(Show_Link = complete_link, User_Reviews = usrv_count, Critic_Reviews = critic[2], Popularity_Rating = pop_rating)) 
}))

shows <- cbind(tv_shows, show_url_df)
shows
```

