---
title: "RWorksheet#5b_group(freires,rocillo,sanico)"
output: html_document
date: "2024-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 1. Select 5 categories from Amazon and select 30 products from each category. 

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

makeup_url <- "https://www.amazon.com/s?k=lipstick&crid=1T047TIYTCQV2&sprefix=lip%2Caps%2C436&ref=nb_sb_ss_ts-doa-p_8_3"

session1 <- bow(makeup_url,
               user_agent = "Educational")
session1
```

```{r}
library(rvest)

amazondf1 <- data.frame()

page1 <- scrape(session1)

description1 <- page1 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text() %>%
  head(30)

description1
```

```{r}
skincare_url <- 
'https://www.amazon.com/s?k=face+mask&rh=n%3A11060451&ref=nb_sb_noss'

session2 <- bow(skincare_url,
               user_agent = "Educational")
print(session2)
```

```{r}
library(rvest)

amazondf2 <- data.frame()

page2 <- scrape(session2)

description2 <- page2 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text() %>%
  head(30)

description2
```

```{r}
fragrance_url <- 'https://www.amazon.com/s?k=women&rh=n%3A11056591&ref=nb_sb_noss'

session3 <- bow(fragrance_url,
               user_agent = "Educational")
print(session3)
```

```{r}
library(rvest)

amazondf3 <- data.frame()

page3 <- scrape(session3)

description3 <- page3 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text() %>%
  head(30)

description3
```

```{r}
nailcare_url <- "https://www.amazon.com/s?k=nail+polish&rh=n%3A17242866011&ref=nb_sb_noss"

session4 <- bow(nailcare_url,
               user_agent = "Educational")

session4
```

```{r}
library(rvest)
amazondf4 <- data.frame()

page4 <- scrape(session4)

description4 <- page4 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text() %>%
  head(30)

description4
```

```{r}
Haircare_url <- "https://www.amazon.com/b/?node=11057971&ref_=Oct_d_odnav_d_11057241_0&pd_rd_w=5q3s3&content-id=amzn1.sym.ed470844-7314-4717-8e3f-b384c77cdbd8&pf_rd_p=ed470844-7314-4717-8e3f-b384c77cdbd8&pf_rd_r=8DGY6JEY6F5GN8HW11E4&pd_rd_wg=UjhVt&pd_rd_r=063e199d-86ac-4c1e-8c00-2d1b9d50f89b"

session5 <- bow(nailcare_url,
               user_agent = "Educational")
print(session5)
```

```{r}
library(rvest)

amazondf5 <- data.frame()

page5 <- scrape(session5)

description5 <- page5 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text() %>%
  head(30)

description5
```

 2. Out of the 30 products, pick 10 products and extract 20 reviews in each one which includes reviewer, date, individual rating, title of review, text review, and verified purchase.

 a.Make_up_category

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product1_url <- 'https://www.amazon.com/Maybelline-Superstay-Long-Lasting-Pigmented-Pathfinder/dp/B07W3PVLW1/ref=sr_1_1_sspa?crid=1T047TIYTCQV2&dib=eyJ2IjoiMSJ9.DUKcUV74BV1EdjFXCPz4bLy7KMO7W9jLitoZ5HhvE-emZKn25YdUIa3En0oxp_vOVvTZOKhzypsMcIJFF-fku5LUM-3-i7Fcp45kgngbHGmn_gSzdL3SAjH5FPJwutSKtlqqYDz8QgDq1XolonfriagprEHYUbOl90nKruGOy6XokUs-IjAy6CJq5Fd_lCA3A9yrIi47r78KQ60UXPONj2fUwHgdDyF62Yf-jg6Dx3kXf0sMyPIXA6qN_GjuZwrjMO0czBoj4VIuMOFqh0tdLucAg96vwKln1ZiO2xwAF1M.7nthZRUdH1HfRFvgQUyw2FqrQvY15tzb7hN0tF2Q2qU&dib_tag=se&keywords=lipstick&qid=1733497736&sprefix=lip%2Caps%2C436&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1'

session1 <- bow(product1_url,
               user_agent = "Educational")
print(session1)
```

```{r}
library(rvest)

product_1 <- scrape(session1)

reviewer <-  product_1%>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_1 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_1 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_1 %>%
    html_nodes('.review-title') %>%
    html_text()
review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_1%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_1 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product1df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

print(Product1df)
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product2_url <- 'https://www.amazon.com/Maybelline-Longwear-No-Budge-Lipcolor-Pigmented/dp/B09QH7SS43/ref=sr_1_2_sspa?crid=1T047TIYTCQV2&dib=eyJ2IjoiMSJ9.DUKcUV74BV1EdjFXCPz4bLy7KMO7W9jLitoZ5HhvE-foV6iYmArZy-6wdTi1n-D4UjkBKVConiSIJLy_RMTrLHMgqjrn8V0pMsC9XhegFg5TrdeWGde4os1GTLam-SusFRmHZcUAMClD7q3B_kISwyuKjnJbiWdNKS8Fa-ewoiQnU6cbjRs4v5iuu1d5ztCeFZhSV7skPR52E_kYQgPpkR5SN2OQIAwHlP0DE_9NCI1iUNJJKHUGPcNRmifNqqnS6h1BgYYzii8FsRcKDconrZ5wSBEWk8-F-e4FbKSUipg.Ogfvug8KUkvQ-AjP5Senp0EvXEGHyzIrS9h5p8Fc3k8&dib_tag=se&keywords=lipstick&qid=1733497444&sprefix=lip%2Caps%2C436&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1'

session2 <- bow(product2_url,
               user_agent = "Educational")
print(session2)
```

```{r}
library(rvest)

product_2 <- scrape(session2)

reviewer <-  product_2 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_2 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_2 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_2 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_2%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_2 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product2df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

print(Product2df)
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product3_url <- 'https://www.amazon.com/Liquid-Lipstick-Long-Lasting-Non-Stick-Waterproof/dp/B083QNQQP9/ref=sr_1_7?crid=1T047TIYTCQV2&dib=eyJ2IjoiMSJ9.DUKcUV74BV1EdjFXCPz4bLy7KMO7W9jLitoZ5HhvE-f5sRfjEX1vbwUBOS59wCcyCJRTrPBDX_Av2wMyl3Ubo3Mgqjrn8V0pMsC9XhegFg7N1LNM3ub8X3spzRZJslfV-FJB5LNDeTOSSfAjJOR_hyuKjnJbiWdNKS8Fa-ewoiQnU6cbjRs4v5iuu1d5ztCeFZhSV7skPR52E_kYQgPpkR5SN2OQIAwHlP0DE_9NCI1iUNJJKHUGPcNRmifNqqnS6h1BgYYzii8FsRcKDconrYj7Ec_y9Nq_7bV4NBEna3A.EQ1pV3ME24iysmz87skE1HaVEDeynnaytlvBjChYtiI&dib_tag=se&keywords=lipstick&qid=1733502170&sprefix=lip%2Caps%2C436&sr=8-7'

session3 <- bow(product3_url,
               user_agent = "Educational")
print(session3)
```

```{r}
library(rvest)

product_3 <- scrape(session3)

reviewer <-  product_3 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_3 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_3 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

review_titles <- product_3 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_3%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_3 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product3df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

print(Product3df)
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product4_url <- 'https://www.amazon.com/Lipstick-FirstFly-Nutritious-Moisturizer-Temperature/dp/B078VR8SHC/ref=sr_1_8?crid=1T047TIYTCQV2&dib=eyJ2IjoiMSJ9.DUKcUV74BV1EdjFXCPz4bLy7KMO7W9jLitoZ5HhvE-f5sRfjEX1vbwUBOS59wCcyCJRTrPBDX_Av2wMyl3Ubo3Mgqjrn8V0pMsC9XhegFg7N1LNM3ub8X3spzRZJslfV-FJB5LNDeTOSSfAjJOR_hyuKjnJbiWdNKS8Fa-ewoiQnU6cbjRs4v5iuu1d5ztCeFZhSV7skPR52E_kYQgPpkR5SN2OQIAwHlP0DE_9NCI1iUNJJKHUGPcNRmifNqqnS6h1BgYYzii8FsRcKDconrYj7Ec_y9Nq_7bV4NBEna3A.EQ1pV3ME24iysmz87skE1HaVEDeynnaytlvBjChYtiI&dib_tag=se&keywords=lipstick&qid=1733502170&sprefix=lip%2Caps%2C436&sr=8-8'

session4 <- bow(product4_url,
               user_agent = "Educational")
print(session4)
```

```{r}
library(rvest)

product_4 <- scrape(session4)

reviewer <-  product_4 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_4 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
rating <- product_4 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_4 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)


text_review <- product_4 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()


verified_purchase <- product_4 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product4df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

print(Product4df)
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product5_url <- "https://www.amazon.com/wet-wild-Hydrating-Formulated-Cruelty-Free/dp/B010GNWPMQ/ref=sr_1_9?crid=1T047TIYTCQV2&dib=eyJ2IjoiMSJ9.DUKcUV74BV1EdjFXCPz4bLy7KMO7W9jLitoZ5HhvE-f5sRfjEX1vbwUBOS59wCcyCJRTrPBDX_Av2wMyl3Ubo3Mgqjrn8V0pMsC9XhegFg7N1LNM3ub8X3spzRZJslfV-FJB5LNDeTOSSfAjJOR_hyuKjnJbiWdNKS8Fa-ewoiQnU6cbjRs4v5iuu1d5ztCeFZhSV7skPR52E_kYQgPpkR5SN2OQIAwHlP0DE_9NCI1iUNJJKHUGPcNRmifNqqnS6h1BgYYzii8FsRcKDconrYj7Ec_y9Nq_7bV4NBEna3A.EQ1pV3ME24iysmz87skE1HaVEDeynnaytlvBjChYt"

session5 <- bow(product4_url,
               user_agent = "Educational")
print(session5)
```

```{r}
library(rvest)

product_5 <- scrape(session5)

reviewer <-  product_5%>%
html_nodes('.a-profile-name') %>%
    html_text()
 
dates <- product_5 %>%
    html_nodes('.review-date') %>%
    html_text()
  
 review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_5 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_5 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_5 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_5 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product5df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

print(Product5df)
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product6_url <- "https://www.amazon.com/LAURA-GELLER-NEW-YORK-Lightweight/dp/B08MHYGT3L/ref=sr_1_10?crid=1T047TIYTCQV2&dib=eyJ2IjoiMSJ9.DUKcUV74BV1EdjFXCPz4bLy7KMO7W9jLitoZ5HhvE-f5sRfjEX1vbwUBOS59wCcyCJRTrPBDX_Av2wMyl3Ubo3Mgqjrn8V0pMsC9XhegFg7N1LNM3ub8X3spzRZJslfV-FJB5LNDeTOSSfAjJOR_hyuKjnJbiWdNKS8Fa-ewoiQnU6cbjRs4v5iuu1d5ztCeFZhSV7skPR52E_kYQgPpkR5SN2OQIAwHlP0DE_9NCI1iUNJJKHUGPcNRmifNqqnS6h1BgYYzii8FsRcKDconrYj7Ec_y9Nq_7bV4NBEna3A.EQ1pV3ME24iysmz87skE1HaVEDeynnaytlvBjChYtiI&dib_tag=se&keywords=lipstick&qid=1733502170&sprefix=lip%2Caps%2C436&sr=8-10"

session6 <- bow(product6_url,
               user_agent = "Educational")
print(session6)
```

```{r}
library(rvest)

product_6 <- scrape(session6)

reviewer <-  product_6 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_6 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_6 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_6 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_6 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_6 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product6df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

print(Product6df)
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product7_url <- "https://www.amazon.com/BINGBRUSH-Longwear-Lipstick-Ultimate-Collection/dp/B0CWNTGGTH/ref=sr_1_14_sspa?crid=1T047TIYTCQV2&dib=eyJ2IjoiMSJ9.DUKcUV74BV1EdjFXCPz4bLy7KMO7W9jLitoZ5HhvE-f5sRfjEX1vbwUBOS59wCcyCJRTrPBDX_Av2wMyl3Ubo3Mgqjrn8V0pMsC9XhegFg7N1LNM3ub8X3spzRZJslfV-FJB5LNDeTOSSfAjJOR_hyuKjnJbiWdNKS8Fa-ewoiQnU6cbjRs4v5iuu1d5ztCeFZhSV7skPR52E_kYQgPpkR5SN2OQIAwHlP0DE_9NCI1iUNJJKHUGPcNRmifNqqnS6h1BgYYzii8FsRcKDconrYj7Ec_y9Nq_7bV4NBEna3A.EQ1pV3ME24iysmz87skE1HaVEDeynnaytlvBjChYtiI&dib_tag=se&keywords=lipstick&qid=1733502170&sprefix=lip%2Caps%2C436&sr=8-14-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1"

session7 <- bow(product7_url,
               user_agent = "Educational")
print(session7)
```

```{r}
library(rvest)

product_7 <- scrape(session7)

reviewer <-  product_7%>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_7 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_7 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_7 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_7 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_7 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product7df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

print(Product7df)
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product8_url <- "https://www.amazon.com/evpct-Velvet-Lipstick-Lasting-Waterproof/dp/B0DBQN64DH/ref=sr_1_22_sspa?crid=1T047TIYTCQV2&dib=eyJ2IjoiMSJ9.DUKcUV74BV1EdjFXCPz4bLy7KMO7W9jLitoZ5HhvE-f5sRfjEX1vbwUBOS59wCcyCJRTrPBDX_Av2wMyl3Ubo3Mgqjrn8V0pMsC9XhegFg7N1LNM3ub8X3spzRZJslfV-FJB5LNDeTOSSfAjJOR_hyuKjnJbiWdNKS8Fa-ewoiQnU6cbjRs4v5iuu1d5ztCeFZhSV7skPR52E_kYQgPpkR5SN2OQIAwHlP0DE_9NCI1iUNJJKHUGPcNRmifNqqnS6h1BgYYzii8FsRcKDconrYj7Ec_y9Nq_7bV4NBEna3A.EQ1pV3ME24iysmz87skE1HaVEDeynnaytlvBjChYtiI&dib_tag=se&keywords=lipstick&qid=1733502170&sprefix=lip%2Caps%2C436&sr=8-22-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1"

session8 <- bow(product8_url,
               user_agent = "Educational")
print(session8)
```

```{r}
library(rvest)

product_8 <- scrape(session8)

reviewer <-  product_8 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_8 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_8 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_8 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_8 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_8 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product8df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

print(Product8df)
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product9_url <- "https://www.amazon.com/Peripera-High-Pigmentation-Lightweight-Moisturizing-PEACHLIGHT/dp/B0B2QWRQVL/ref=sr_1_2_sspa?crid=1T047TIYTCQV2&dib=eyJ2IjoiMSJ9.DUKcUV74BV1EdjFXCPz4bLy7KMO7W9jLitoZ5HhvE-f5sRfjEX1vbwUBOS59wCcyCJRTrPBDX_Av2wMyl3Ubo3Mgqjrn8V0pMsC9XhegFg7N1LNM3ub8X3spzRZJslfV-FJB5LNDeTOSSfAjJOR_hyuKjnJbiWdNKS8Fa-ewoiQnU6cbjRs4v5iuu1d5ztCeFZhSV7skPR52E_kYQgPpkR5SN2OQIAwHlP0DE_9NCI1iUNJJKHUGPcNRmifNqqnS6h1BgYYzii8FsRcKDconrYj7Ec_y9Nq_7bV4NBEna3A.EQ1pV3ME24iysmz87skE1HaVEDeynnaytlvBjChYtiI&dib_tag=se&keywords=lipstick&qid=1733502170&sprefix=lip%2Caps%2C436&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1"

session9 <- bow(product9_url,
               user_agent = "Educational")
print(session9)
```

```{r}
library(rvest)

product_9 <- scrape(session9)

reviewer <-  product_9 %>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_9 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_9 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_9 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_9 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_9 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product9df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

print(Product9df)
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product10_url <- 'https://www.amazon.com/Flower-Knows-Gloss-Glowy-Moisturizing-Lacquer-Hydrating/dp/B0DDPLLJJ7/ref=sr_1_20_sspa?crid=1T047TIYTCQV2&dib=eyJ2IjoiMSJ9.DUKcUV74BV1EdjFXCPz4bLy7KMO7W9jLitoZ5HhvE-f5sRfjEX1vbwUBOS59wCcyCJRTrPBDX_Av2wMyl3Ubo3Mgqjrn8V0pMsC9XhegFg7N1LNM3ub8X3spzRZJslfV-FJB5LNDeTOSSfAjJOR_hyuKjnJbiWdNKS8Fa-ewoiQnU6cbjRs4v5iuu1d5ztCeFZhSV7skPR52E_kYQgPpkR5SN2OQIAwHlP0DE_9NCI1iUNJJKHUGPcNRmifNqqnS6h1BgYYzii8FsRcKDconrYj7Ec_y9Nq_7bV4NBEna3A.EQ1pV3ME24iysmz87skE1HaVEDeynnaytlvBjChYtiI&dib_tag=se&keywords=lipstick&qid=1733502170&sprefix=lip%2Caps%2C436&sr=8-20-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1'


session10 <- bow(product10_url,
               user_agent = "Educational")
print(session10)
```

```{r}
library(rvest)

product_10 <- scrape(session10)

reviewer <-  product_10 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_10 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_10 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_10 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_10 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_10 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product10df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

print(Product10df)
```

b. Skincare_category
```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product1_url <- 
'https://www.amazon.com/Maybelline-Superstay-Long-Lasting-Pigmented-Pathfinder/dp/B07W3PVLW1/ref=sr_1_1_sspa?crid=1T047TIYTCQV2&dib=eyJ2IjoiMSJ9.DUKcUV74BV1EdjFXCPz4bLy7KMO7W9jLitoZ5HhvE-emZKn25YdUIa3En0oxp_vOVvTZOKhzypsMcIJFF-fku5LUM-3-i7Fcp45kgngbHGmn_gSzdL3SAjH5FPJwutSKtlqqYDz8QgDq1XolonfriagprEHYUbOl90nKruGOy6XokUs-IjAy6CJq5Fd_lCA3A9yrIi47r78KQ60UXPONj2fUwHgdDyF62Yf-jg6Dx3kXf0sMyPIXA6qN_GjuZwrjMO0czBoj4VIuMOFqh0tdLucAg96vwKln1ZiO2xwAF1M.7nthZRUdH1HfRFvgQUyw2FqrQvY15tzb7hN0tF2Q2qU&dib_tag=se&keywords=lipstick&qid=1733497736&sprefix=lip%2Caps%2C436&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1'

session1 <- bow(product1_url,
               user_agent = "Educational")
session1
```

```{r}
library(rvest)

product_1 <- scrape(session1)

reviewer <-  product_1%>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_1 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_1 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_1 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_1%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_1 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product1df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product1df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product2_url <- 
  'https://www.amazon.com/Ebanel-Moisturizing-Hyaluronic-Brightening-Anti-Wrinkle/dp/B01N37AK8V/ref=sr_1_2_sspa?dib=eyJ2IjoiMSJ9.esd3YMfCkqJmlK7yugxSYDE_fPdIDvKtx6sUVtKQ_6pF88IqlDillp45q6X8sYFu6H50a42IaqSHLdHkzVyv8CgWLqsxL4HiqDCNwUq1kk-MLumfO-Dol4FoHMXXcYNmszcvwluwocKIUpPGA9agrcF7IIRe_2TQf8XLZxJy3P2_Cr4mJ7H2StBPdoFc4clt6d-tSh9tG2uU9HQpctVlYuv7g-w2TlOrQvJnTQEWI4g5TkjJ1_Muw2nIhHGm3XT511PwxcOnH8ssZA9NSWVodgD15mVZjjGpdcgzrJXYr3I.IyeS6ACfkJZEGK0WvLQ6RDFE1MrrAtp3jPWtNt4io1M&dib_tag=se&keywords=face+mask&qid=1733714445&s=beauty&sr=1-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1'

session2 <- bow(product2_url,
               user_agent = "Educational")
session2
```

```{r}
library(rvest)

product_2 <- scrape(session2)

reviewer <-  product_2 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_2 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_2 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_2 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_2%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_2 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product2df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product2df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product3_url <- 
  "https://www.amazon.com/TULA-Skin-H2Oasis-Instant-Reviving/dp/B0CQ8R62RR/ref=sr_1_3_sspa?dib=eyJ2IjoiMSJ9.esd3YMfCkqJmlK7yugxSYDE_fPdIDvKtx6sUVtKQ_6pF88IqlDillp45q6X8sYFu6H50a42IaqSHLdHkzVyv8CgWLqsxL4HiqDCNwUq1kk-MLumfO-Dol4FoHMXXcYNmszcvwluwocKIUpPGA9agrcF7IIRe_2TQf8XLZxJy3P2_Cr4mJ7H2StBPdoFc4clt6d-tSh9tG2uU9HQpctVlYuv7g-w2TlOrQvJnTQEWI4g5TkjJ1_Muw2nIhHGm3XT511PwxcOnH8ssZA9NSWVodgD15mVZjjGpdcgzrJXYr3I.IyeS6ACfkJZEGK0WvLQ6RDFE1MrrAtp3jPWtNt4io1M&dib_tag=se&keywords=face+mask&qid=1733714445&s=beauty&sr=1-3-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1"

session3 <- bow(product3_url,
               user_agent = "Educational")
session3
```

```{r}
library(rvest)

product_3 <- scrape(session3)

reviewer <-  product_3%>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_3 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_3 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
review_titles <- product_3 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_3%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_3 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product3df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product3df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product4_url <- 
  "https://www.amazon.com/Litepak-Premium-Disposable-Masks-Boxes/dp/B084YVG3H1/ref=sr_1_4_sspa?dib=eyJ2IjoiMSJ9.esd3YMfCkqJmlK7yugxSYDE_fPdIDvKtx6sUVtKQ_6pF88IqlDillp45q6X8sYFu6H50a42IaqSHLdHkzVyv8CgWLqsxL4HiqDCNwUq1kk-MLumfO-Dol4FoHMXXcYNmszcvwluwocKIUpPGA9agrcF7IIRe_2TQf8XLZxJy3P2_Cr4mJ7H2StBPdoFc4clt6d-tSh9tG2uU9HQpctVlYuv7g-w2TlOrQvJnTQEWI4g5TkjJ1_Muw2nIhHGm3XT511PwxcOnH8ssZA9NSWVodgD15mVZjjGpdcgzrJXYr3I.IyeS6ACfkJZEGK0WvLQ6RDFE1MrrAtp3jPWtNt4io1M&dib_tag=se&keywords=face+mask&qid=1733714445&s=beauty&sr=1-4-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1"
session4 <- bow(product4_url,
               user_agent = "Educational")
session4
```

```{r}
library(rvest)

product_4 <- scrape(session4)

reviewer <-  product_4  %>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_4 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_4 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_4 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_4 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_4 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product4df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product4df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product5_url <- 
  "https://www.amazon.com/Geologie-Micro-Exfoliator-Minute-Eucalyptus/dp/B0BL8F3NJP/ref=sr_1_14_sspa?dib=eyJ2IjoiMSJ9.esd3YMfCkqJmlK7yugxSYDE_fPdIDvKtx6sUVtKQ_6pF88IqlDillp45q6X8sYFu6H50a42IaqSHLdHkzVyv8CgWLqsxL4HiqDCNwUq1kk-MLumfO-Dol4FoHMXXcYNmszcvwluwocKIUpPGA9agrcF7IIRe_2TQf8XLZxJy3P2_Cr4mJ7H2StBPdoFc4clt6d-tSh9tG2uU9HQpctVlYuv7g-w2TlOrQvJnTQEWI4g5TkjJ1_Muw2nIhHGm3XT511PwxcOnH8ssZA9NSWVodgD15mVZjjGpdcgzrJXYr3I.IyeS6ACfkJZEGK0WvLQ6RDFE1MrrAtp3jPWtNt4io1M&dib_tag=se&keywords=face+mask&qid=1733714445&s=beauty&sr=1-14-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1"

session5 <- bow(product5_url,
               user_agent = "Educational")
session5
```

```{r}
library(rvest)

product_5 <- scrape(session5)

reviewer <-  product_5 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_5 %>%
    html_nodes('.review-date') %>%
    html_text()
  
 review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_5 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_5 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_5 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_5 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product5df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product5df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product6_url <- 
  "https://www.amazon.com/ZealSea-Facial-Brightening-Hydrating-Collagen/dp/B0967HYR5M/ref=sr_1_7?dib=eyJ2IjoiMSJ9.esd3YMfCkqJmlK7yugxSYDE_fPdIDvKtx6sUVtKQ_6pF88IqlDillp45q6X8sYFu6H50a42IaqSHLdHkzVyv8CgWLqsxL4HiqDCNwUq1kk-MLumfO-Dol4FoHMXXcYNmszcvwluwocKIUpPGA9agrcF7IIRe_2TQf8XLZxJy3P2_Cr4mJ7H2StBPdoFc4clt6d-tSh9tG2uU9HQpctVlYuv7g-w2TlOrQvJnTQEWI4g5TkjJ1_Muw2nIhHGm3XT511PwxcOnH8ssZA9NSWVodgD15mVZjjGpdcgzrJXYr3I.IyeS6ACfkJZEGK0WvLQ6RDFE1MrrAtp3jPWtNt4io1M&dib_tag=se&keywords=face+mask&qid=1733714445&s=beauty&sr=1-7"

session6 <- bow(product6_url,
               user_agent = "Educational")
session6
```

```{r}
library(rvest)

product_6 <- scrape(session6)

reviewer <-  product_6 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_6 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_6 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_6 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_6 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_6 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product6df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product6df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product7_url <- 
  "https://www.amazon.com/ELEMIS-Superfood-Vital-Veggie-Mask/dp/B07L7WTCDR/ref=sr_1_11_sspa?dib=eyJ2IjoiMSJ9.esd3YMfCkqJmlK7yugxSYDE_fPdIDvKtx6sUVtKQ_6pF88IqlDillp45q6X8sYFu6H50a42IaqSHLdHkzVyv8CgWLqsxL4HiqDCNwUq1kk-MLumfO-Dol4FoHMXXcYNmszcvwluwocKIUpPGA9agrcF7IIRe_2TQf8XLZxJy3P2_Cr4mJ7H2StBPdoFc4clt6d-tSh9tG2uU9HQpctVlYuv7g-w2TlOrQvJnTQEWI4g5TkjJ1_Muw2nIhHGm3XT511PwxcOnH8ssZA9NSWVodgD15mVZjjGpdcgzrJXYr3I.IyeS6ACfkJZEGK0WvLQ6RDFE1MrrAtp3jPWtNt4io1M&dib_tag=se&keywords=face+mask&qid=1733714445&s=beauty&sr=1-11-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1"

session7 <- bow(product7_url,
               user_agent = "Educational")
session7
```

```{r}
library(rvest)

product_7 <- scrape(session7)

reviewer <-  product_7 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_7 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_7 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_7 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_7 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_7 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product7df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product7df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product8_url <- 
  "https://www.amazon.com/OOTD-Hydrating-Collagen-Hyaluronic-Certified/dp/B0B41LVMJ3/ref=sr_1_13_sspa?dib=eyJ2IjoiMSJ9.esd3YMfCkqJmlK7yugxSYDE_fPdIDvKtx6sUVtKQ_6pF88IqlDillp45q6X8sYFu6H50a42IaqSHLdHkzVyv8CgWLqsxL4HiqDCNwUq1kk-MLumfO-Dol4FoHMXXcYNmszcvwluwocKIUpPGA9agrcF7IIRe_2TQf8XLZxJy3P2_Cr4mJ7H2StBPdoFc4clt6d-tSh9tG2uU9HQpctVlYuv7g-w2TlOrQvJnTQEWI4g5TkjJ1_Muw2nIhHGm3XT511PwxcOnH8ssZA9NSWVodgD15mVZjjGpdcgzrJXYr3I.IyeS6ACfkJZEGK0WvLQ6RDFE1MrrAtp3jPWtNt4io1M&dib_tag=se&keywords=face+mask&qid=1733714445&s=beauty&sr=1-13-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1"

session8 <- bow(product8_url,
               user_agent = "Educational")
session8
```

```{r}
library(rvest)

product_8 <- scrape(session8)

reviewer <-  product_8 %>%
html_nodes('.a-profile-name') %>%
    html_text()
 
dates <- product_8 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_8 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_8 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_8 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_8 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product8df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product8df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product9_url <- 
  "https://www.amazon.com/Eight-Saints-Reducing-Blemishes-Impurities/dp/B08YS2SZXF/ref=sr_1_21_sspa?dib=eyJ2IjoiMSJ9.esd3YMfCkqJmlK7yugxSYDE_fPdIDvKtx6sUVtKQ_6pF88IqlDillp45q6X8sYFu6H50a42IaqSHLdHkzVyv8CgWLqsxL4HiqDCNwUq1kk-MLumfO-Dol4FoHMXXcYNmszcvwluwocKIUpPGA9agrcF7IIRe_2TQf8XLZxJy3P2_Cr4mJ7H2StBPdoFc4clt6d-tSh9tG2uU9HQpctVlYuv7g-w2TlOrQvJnTQEWI4g5TkjJ1_Muw2nIhHGm3XT511PwxcOnH8ssZA9NSWVodgD15mVZjjGpdcgzrJXYr3I.IyeS6ACfkJZEGK0WvLQ6RDFE1MrrAtp3jPWtNt4io1M&dib_tag=se&keywords=face+mask&qid=1733714445&s=beauty&sr=1-21-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1"

session9 <- bow(product9_url,
               user_agent = "Educational")
session9
```

```{r}
library(rvest)

product_9 <- scrape(session9)

reviewer <-  product_9 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_9 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_9 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_9 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_9 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_9 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product9df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product9df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product10_url <- 
  "https://www.amazon.com/Turmeric-Vitamin-SHVYOG-Controlling-Refining/dp/B08YRD11VS/ref=sr_1_25?dib=eyJ2IjoiMSJ9.esd3YMfCkqJmlK7yugxSYDE_fPdIDvKtx6sUVtKQ_6pF88IqlDillp45q6X8sYFu6H50a42IaqSHLdHkzVyv8CgWLqsxL4HiqDCNwUq1kk-MLumfO-Dol4FoHMXXcYNmszcvwluwocKIUpPGA9agrcF7IIRe_2TQf8XLZxJy3P2_Cr4mJ7H2StBPdoFc4clt6d-tSh9tG2uU9HQpctVlYuv7g-w2TlOrQvJnTQEWI4g5TkjJ1_Muw2nIhHGm3XT511PwxcOnH8ssZA9NSWVodgD15mVZjjGpdcgzrJXYr3I.IyeS6ACfkJZEGK0WvLQ6RDFE1MrrAtp3jPWtNt4io1M&dib_tag=se&keywords=face+mask&qid=1733714445&s=beauty&sr=1-25"

session10 <- bow(product10_url,
               user_agent = "Educational")
session10
```

```{r}
library(rvest)

product_10 <- scrape(session10)

reviewer <-  product_10 %>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_10 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_10 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_10 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_10 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_10 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 
```

```{r}
Product10df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product10df
```

 c. fragrance_url 

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product1_url <-  "https://www.amazon.com/Lanc%C3%B4me-Belle-Parfum-Spray-Ounce/dp/B00I7PK3GQ/ref=sr_1_1?dib=eyJ2IjoiMSJ9.UXOoBxiapianaMwZaQMwx_4hwzJXQurb-pMMSE2uZskqK7Am9_nJccjGee-ZzvM0o4jOBZb7vQENpffT2Nrnx7RkgtGV3Ck7nI_7CrSAWMnMn67XXDvVBBym-iFM8Hd1h6nRhU2sNVGYFOHEsDStB5tYKe0ogoItJX0EGoZNPbUEB570yyI2solJqrA-qI77gI0j1xtjvvLzuRkrFCaEqHXPA_NisxPOLr3ECUc5Yp8dvH-Y_MZZIyrMO1hTxZosbAtNLBTDaG3p6f3cghtvaePklfu91IqhdmBNgsWrDhs.95N-e_fBAlIyz_jJLyTC_s-2NQrXRkw1xDRydoXVEKk&dib_tag=se&keywords=women&qid=1733849037&s=beauty&sr=1-1&th=1"

session1 <- bow(product1_url,
               user_agent = "Educational")
session1
```

```{r}
library(rvest)

product_1 <- scrape(session1)

reviewer <-  product_1%>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_1 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_1 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_1 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_1%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_1 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 

Product1df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product1df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product2_url <- 
	"https://www.amazon.com/Victorias-Secret-Bombshell-2-5oz-Travel/dp/B0048B4XYQ/ref=sr_1_2?dib=eyJ2IjoiMSJ9.UXOoBxiapianaMwZaQMwx_4hwzJXQurb-pMMSE2uZskqK7Am9_nJccjGee-ZzvM0o4jOBZb7vQENpffT2Nrnx7RkgtGV3Ck7nI_7CrSAWMnMn67XXDvVBBym-iFM8Hd1h6nRhU2sNVGYFOHEsDStB5tYKe0ogoItJX0EGoZNPbUEB570yyI2solJqrA-qI77gI0j1xtjvvLzuRkrFCaEqHXPA_NisxPOLr3ECUc5Yp8dvH-Y_MZZIyrMO1hTxZosbAtNLBTDaG3p6f3cghtvaePklfu91IqhdmBNgsWrDhs.95N-e_fBAlIyz_jJLyTC_s-2NQrXRkw1xDRydoXVEKk&dib_tag=se&keywords=women&qid=1733849037&s=beauty&sr=1-2"

session2 <- bow(product2_url,
               user_agent = "Educational")
session2
```

```{r}
library(rvest)

product_2 <- scrape(session2)

reviewer <-  product_2 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_2 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_2 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_2 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_2%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_2 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 

Product2df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product2df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product3_url <- "https://www.amazon.com/Calvin-Klein-ETERNITY-Eau-Parfum/dp/B00021AJ5I/ref=sr_1_4?dib=eyJ2IjoiMSJ9.UXOoBxiapianaMwZaQMwx_4hwzJXQurb-pMMSE2uZskqK7Am9_nJccjGee-ZzvM0o4jOBZb7vQENpffT2Nrnx7RkgtGV3Ck7nI_7CrSAWMnMn67XXDvVBBym-iFM8Hd1h6nRhU2sNVGYFOHEsDStB5tYKe0ogoItJX0EGoZNPbUEB570yyI2solJqrA-qI77gI0j1xtjvvLzuRkrFCaEqHXPA_NisxPOLr3ECUc5Yp8dvH-Y_MZZIyrMO1hTxZosbAtNLBTDaG3p6f3cghtvaePklfu91IqhdmBNgsWrDhs.95N-e_fBAlIyz_jJLyTC_s-2NQrXRkw1xDRydoXVEKk&dib_tag=se&keywords=women&qid=1733849037&s=beauty&sr=1-4"

session3 <- bow(product3_url,
               user_agent = "Educational")
session3
```

```{r}
library(rvest)

product_3 <- scrape(session3)

reviewer <-  product_3 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_3 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_3 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
review_titles <- product_3 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_3%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_3 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product3df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product3df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product4_url <- "https://www.amazon.com/Calvin-Klein-ETERNITY-Eau-Parfum/dp/B00021AJ5I/ref=sr_1_4?dib=eyJ2IjoiMSJ9.UXOoBxiapianaMwZaQMwx_4hwzJXQurb-pMMSE2uZskqK7Am9_nJccjGee-ZzvM0o4jOBZb7vQENpffT2Nrnx7RkgtGV3Ck7nI_7CrSAWMnMn67XXDvVBBym-iFM8Hd1h6nRhU2sNVGYFOHEsDStB5tYKe0ogoItJX0EGoZNPbUEB570yyI2solJqrA-qI77gI0j1xtjvvLzuRkrFCaEqHXPA_NisxPOLr3ECUc5Yp8dvH-Y_MZZIyrMO1hTxZosbAtNLBTDaG3p6f3cghtvaePklfu91IqhdmBNgsWrDhs.95N-e_fBAlIyz_jJLyTC_s-2NQrXRkw1xDRydoXVEKk&dib_tag=se&keywords=women&qid=1733849037&s=beauty&sr=1-4"
 
session4 <- bow(product4_url,
               user_agent = "Educational")
session4
```

```{r}
library(rvest)

product_4 <- scrape(session4)

reviewer <-  product_4 %>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_4 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_4 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_4 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_4 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_4 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product4df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product4df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product5_url <- "https://www.amazon.com/Victorias-Secret-Bombshell-Intense-Parfum/dp/B07XC2RYLF/ref=sr_1_7?dib=eyJ2IjoiMSJ9.UXOoBxiapianaMwZaQMwx_4hwzJXQurb-pMMSE2uZskqK7Am9_nJccjGee-ZzvM0o4jOBZb7vQENpffT2Nrnx7RkgtGV3Ck7nI_7CrSAWMnMn67XXDvVBBym-iFM8Hd1h6nRhU2sNVGYFOHEsDStB5tYKe0ogoItJX0EGoZNPbUEB570yyI2solJqrA-qI77gI0j1xtjvvLzuRkrFCaEqHXPA_NisxPOLr3ECUc5Yp8dvH-Y_MZZIyrMO1hTxZosbAtNLBTDaG3p6f3cghtvaePklfu91IqhdmBNgsWrDhs.95N-e_fBAlIyz_jJLyTC_s-2NQrXRkw1xDRydoXVEKk&dib_tag=se&keywords=women&qid=1733849037&s=beauty&sr=1-7"

session5 <- bow(product4_url,
               user_agent = "Educational")
session5
```

```{r}
library(rvest)

product_5 <- scrape(session5)

reviewer <-  product_5%>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_5 %>%
    html_nodes('.review-date') %>%
    html_text()
  
 review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_5 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_5 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_5 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_5 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product5df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product5df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product6_url <- "https://www.amazon.com/Michael-Kors-Wonderlust-Parfum-Spray/dp/B00RK1C3AW/ref=sr_1_8?dib=eyJ2IjoiMSJ9.UXOoBxiapianaMwZaQMwx_4hwzJXQurb-pMMSE2uZskqK7Am9_nJccjGee-ZzvM0o4jOBZb7vQENpffT2Nrnx7RkgtGV3Ck7nI_7CrSAWMnMn67XXDvVBBym-iFM8Hd1h6nRhU2sNVGYFOHEsDStB5tYKe0ogoItJX0EGoZNPbUEB570yyI2solJqrA-qI77gI0j1xtjvvLzuRkrFCaEqHXPA_NisxPOLr3ECUc5Yp8dvH-Y_MZZIyrMO1hTxZosbAtNLBTDaG3p6f3cghtvaePklfu91IqhdmBNgsWrDhs.95N-e_fBAlIyz_jJLyTC_s-2NQrXRkw1xDRydoXVEKk&dib_tag=se&keywords=women&qid=1733849037&s=beauty&sr=1-8"

session6 <- bow(product6_url,
               user_agent = "Educational")
session6
```

```{r}
library(rvest)

product_6 <- scrape(session6)

reviewer <-  product_6 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_6 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_6 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_6 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_6 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_6 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product6df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product6df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product7_url <- "https://www.amazon.com/Ralph-Lauren-Women-Toilette-Natural/dp/B000C1W3OS/ref=sr_1_9?dib=eyJ2IjoiMSJ9.UXOoBxiapianaMwZaQMwx_4hwzJXQurb-pMMSE2uZskqK7Am9_nJccjGee-ZzvM0o4jOBZb7vQENpffT2Nrnx7RkgtGV3Ck7nI_7CrSAWMnMn67XXDvVBBym-iFM8Hd1h6nRhU2sNVGYFOHEsDStB5tYKe0ogoItJX0EGoZNPbUEB570yyI2solJqrA-qI77gI0j1xtjvvLzuRkrFCaEqHXPA_NisxPOLr3ECUc5Yp8dvH-Y_MZZIyrMO1hTxZosbAtNLBTDaG3p6f3cghtvaePklfu91IqhdmBNgsWrDhs.95N-e_fBAlIyz_jJLyTC_s-2NQrXRkw1xDRydoXVEKk&dib_tag=se&keywords=women&qid=1733849037&s=beauty&sr=1-9"

session7 <- bow(product7_url,
               user_agent = "Educational")
session7
```

```{r}
library(rvest)

product_7 <- scrape(session7)

reviewer <-  product_7%>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_7 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_7 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_7 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_7 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_7 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product7df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product7df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product8_url <- "https://www.amazon.com/Marc-Jacobs-Perfect-Parfum-Spray/dp/B08GKZ1233/ref=sr_1_10?dib=eyJ2IjoiMSJ9.UXOoBxiapianaMwZaQMwx_4hwzJXQurb-pMMSE2uZskqK7Am9_nJccjGee-ZzvM0o4jOBZb7vQENpffT2Nrnx7RkgtGV3Ck7nI_7CrSAWMnMn67XXDvVBBym-iFM8Hd1h6nRhU2sNVGYFOHEsDStB5tYKe0ogoItJX0EGoZNPbUEB570yyI2solJqrA-qI77gI0j1xtjvvLzuRkrFCaEqHXPA_NisxPOLr3ECUc5Yp8dvH-Y_MZZIyrMO1hTxZosbAtNLBTDaG3p6f3cghtvaePklfu91IqhdmBNgsWrDhs.95N-e_fBAlIyz_jJLyTC_s-2NQrXRkw1xDRydoXVEKk&dib_tag=se&keywords=women&qid=1733849037&s=beauty&sr=1-10"

session8 <- bow(product8_url,
               user_agent = "Educational")
session8
```

```{r}
library(rvest)

product_8 <- scrape(session8)

reviewer <-  product_8 %>%
html_nodes('.a-profile-name') %>%
    html_text()
 
dates <- product_8 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_8 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_8 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_8 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_8 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product8df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product8df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product9_url <- "https://www.amazon.com/Molton-Brown-Travel-Body-Collection/dp/B0C6TTRYW7/ref=sr_1_11_sspa?dib=eyJ2IjoiMSJ9.UXOoBxiapianaMwZaQMwx_4hwzJXQurb-pMMSE2uZskqK7Am9_nJccjGee-ZzvM0o4jOBZb7vQENpffT2Nrnx7RkgtGV3Ck7nI_7CrSAWMnMn67XXDvVBBym-iFM8Hd1h6nRhU2sNVGYFOHEsDStB5tYKe0ogoItJX0EGoZNPbUEB570yyI2solJqrA-qI77gI0j1xtjvvLzuRkrFCaEqHXPA_NisxPOLr3ECUc5Yp8dvH-Y_MZZIyrMO1hTxZosbAtNLBTDaG3p6f3cghtvaePklfu91IqhdmBNgsWrDhs.95N-e_fBAlIyz_jJLyTC_s-2NQrXRkw1xDRydoXVEKk&dib_tag=se&keywords=women&qid=1733849037&s=beauty&sr=1-11-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1"

session9 <- bow(product9_url,
               user_agent = "Educational")
session9
```

```{r}
library(rvest)

product_9 <- scrape(session9)

reviewer <-  product_9 %>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_9 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_9 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_9 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_9 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_9 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 

Product9df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product9df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product10_url <- "https://www.amazon.com/Thierry-Mugler-Eau-Parfum-Alien/dp/B08ZXY1B7H/ref=sr_1_15?dib=eyJ2IjoiMSJ9.UXOoBxiapianaMwZaQMwx_4hwzJXQurb-pMMSE2uZskqK7Am9_nJccjGee-ZzvM0o4jOBZb7vQENpffT2Nrnx7RkgtGV3Ck7nI_7CrSAWMnMn67XXDvVBBym-iFM8Hd1h6nRhU2sNVGYFOHEsDStB5tYKe0ogoItJX0EGoZNPbUEB570yyI2solJqrA-qI77gI0j1xtjvvLzuRkrFCaEqHXPA_NisxPOLr3ECUc5Yp8dvH-Y_MZZIyrMO1hTxZosbAtNLBTDaG3p6f3cghtvaePklfu91IqhdmBNgsWrDhs.95N-e_fBAlIyz_jJLyTC_s-2NQrXRkw1xDRydoXVEKk&dib_tag=se&keywords=women&qid=1733849037&s=beauty&sr=1-15"

session10 <- bow(product10_url,
               user_agent = "Educational")
session10
```

```{r}
library(rvest)

product_10 <- scrape(session10)

reviewer <-  product_10 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_10 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_10 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_10 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_10 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_10 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product10df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product10df
```

d. nailcare_url 

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product1_url <- "https://www.amazon.com/THERAPISPA-Professional-Cuticle-Strengthen-Cuticles/dp/B0CLHFYBCV/ref=sr_1_11_sspa?dib=eyJ2IjoiMSJ9.Ay87Sh-z2Ng0pSHB2I3WeDa8bxbVpUdRN3fBdHyA7B3uxr7m17hMAUKd5UOhfyG6SxK6hqJso0VC31mRrEuBoNlVFtfghfDz20N6AZMrt_lJSklvLa9G-sbkUXDCLtsxcb4-GLH1FE2Y7gljSfaGjMd_4zU3MKN-TMqfdJd7Ctn-IpxWFQA0qHeT7KkrJW0Gd2qMt3sbgxJhbvheP-AXbOL6_yuJ7lobsb7dUYOgs9STxvKmEcxlTc-ckBsJqU31BpQlFOpgcHLNvNbjVYMOne0WSiQ8FumSTkSibZ13_Do.v4lCQDQf-1QeaqdPiGTRmnOitw77meOSLmWaPEotIyY&dib_tag=se&keywords=nail+polish&qid=1733849894&s=beauty&sr=1-11-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1"

session1 <- bow(product1_url,
               user_agent = "Educational")
session1
```

```{r}
library(rvest)

product_1 <- scrape(session1)

reviewer <-  product_1%>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_1 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_1 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_1 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_1%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_1 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product1df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product1df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product2_url <- "https://www.amazon.com/LACCOVER-ONE-SHOT-CATRINA-COLLECTION/dp/B09YR58MJZ/ref=sr_1_1_sspa?dib=eyJ2IjoiMSJ9.Ay87Sh-z2Ng0pSHB2I3WeDa8bxbVpUdRN3fBdHyA7B3uxr7m17hMAUKd5UOhfyG6SxK6hqJso0VC31mRrEuBoNlVFtfghfDz20N6AZMrt_lJSklvLa9G-sbkUXDCLtsxcb4-GLH1FE2Y7gljSfaGjMd_4zU3MKN-TMqfdJd7Ctn-IpxWFQA0qHeT7KkrJW0Gd2qMt3sbgxJhbvheP-AXbOL6_yuJ7lobsb7dUYOgs9STxvKmEcxlTc-ckBsJqU31BpQlFOpgcHLNvNbjVYMOne0WSiQ8FumSTkSibZ13_Do.v4lCQDQf-1QeaqdPiGTRmnOitw77meOSLmWaPEotIyY&dib_tag=se&keywords=nail+polish&qid=1733849894&s=beauty&sr=1-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1"
	
session2 <- bow(product2_url,
               user_agent = "Educational")
session2
```

```{r}
library(rvest)

product_2 <- scrape(session2)

reviewer <-  product_2 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_2 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_2 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_2 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_2%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_2 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product2df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product2df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product3_url <- "https://www.amazon.com/modelones-Burgundy-Christmas-Champagne-Manicure/dp/B0D5QMDF95/ref=sr_1_2_sspa?dib=eyJ2IjoiMSJ9.Ay87Sh-z2Ng0pSHB2I3WeDa8bxbVpUdRN3fBdHyA7B3uxr7m17hMAUKd5UOhfyG6SxK6hqJso0VC31mRrEuBoNlVFtfghfDz20N6AZMrt_lJSklvLa9G-sbkUXDCLtsxcb4-GLH1FE2Y7gljSfaGjMd_4zU3MKN-TMqfdJd7Ctn-IpxWFQA0qHeT7KkrJW0Gd2qMt3sbgxJhbvheP-AXbOL6_yuJ7lobsb7dUYOgs9STxvKmEcxlTc-ckBsJqU31BpQlFOpgcHLNvNbjVYMOne0WSiQ8FumSTkSibZ13_Do.v4lCQDQf-1QeaqdPiGTRmnOitw77meOSLmWaPEotIyY&dib_tag=se&keywords=nail+polish&qid=1733849894&s=beauty&sr=1-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1"
	
session3 <- bow(product3_url,
               user_agent = "Educational")
session3
```

```{r}
library(rvest)

product_3 <- scrape(session3)

reviewer <-  product_3 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_3 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_3 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
review_titles <- product_3 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_3%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_3 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product3df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product3df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product4_url <- "https://www.amazon.com/Nail-Supply-Portable-Rechargeable-Cordless/dp/B0DH8PT8NF/ref=sr_1_3_sspa?dib=eyJ2IjoiMSJ9.Ay87Sh-z2Ng0pSHB2I3WeDa8bxbVpUdRN3fBdHyA7B3uxr7m17hMAUKd5UOhfyG6SxK6hqJso0VC31mRrEuBoNlVFtfghfDz20N6AZMrt_lJSklvLa9G-sbkUXDCLtsxcb4-GLH1FE2Y7gljSfaGjMd_4zU3MKN-TMqfdJd7Ctn-IpxWFQA0qHeT7KkrJW0Gd2qMt3sbgxJhbvheP-AXbOL6_yuJ7lobsb7dUYOgs9STxvKmEcxlTc-ckBsJqU31BpQlFOpgcHLNvNbjVYMOne0WSiQ8FumSTkSibZ13_Do.v4lCQDQf-1QeaqdPiGTRmnOitw77meOSLmWaPEotIyY&dib_tag=se&keywords=nail+polish&qid=1733849894&s=beauty&sr=1-3-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1"
	 
session4 <- bow(product4_url,
               user_agent = "Educational")
session4
```

```{r}
library(rvest)

product_4 <- scrape(session4)

reviewer <-  product_4 %>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_4 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_4 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_4 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)


text_review <- product_4 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_4 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product4df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product4df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product5_url <- "https://www.amazon.com/AZUREBEAUTY-Glitter-Fingernail-Strengthening-Treatment/dp/B0D2KM8N7S/ref=sr_1_4_sspa?dib=eyJ2IjoiMSJ9.Ay87Sh-z2Ng0pSHB2I3WeDa8bxbVpUdRN3fBdHyA7B3uxr7m17hMAUKd5UOhfyG6SxK6hqJso0VC31mRrEuBoNlVFtfghfDz20N6AZMrt_lJSklvLa9G-sbkUXDCLtsxcb4-GLH1FE2Y7gljSfaGjMd_4zU3MKN-TMqfdJd7Ctn-IpxWFQA0qHeT7KkrJW0Gd2qMt3sbgxJhbvheP-AXbOL6_yuJ7lobsb7dUYOgs9STxvKmEcxlTc-ckBsJqU31BpQlFOpgcHLNvNbjVYMOne0WSiQ8FumSTkSibZ13_Do.v4lCQDQf-1QeaqdPiGTRmnOitw77meOSLmWaPEotIyY&dib_tag=se&keywords=nail+polish&qid=1733849894&s=beauty&sr=1-4-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1"
	
session5 <- bow(product4_url,
               user_agent = "Educational")
session5
```

```{r}
library(rvest)

product_5 <- scrape(session5)

reviewer <-  product_5%>%
html_nodes('.a-profile-name') %>%
    html_text()
 
dates <- product_5 %>%
    html_nodes('.review-date') %>%
    html_text()
  
 review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_5 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_5 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_5 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_5 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product5df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product5df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product6_url <- "https://www.amazon.com/Morovan-Polish-0-25oz-Glossy-Manicure/dp/B0BHT5Z9TR/ref=sr_1_5?dib=eyJ2IjoiMSJ9.Ay87Sh-z2Ng0pSHB2I3WeDa8bxbVpUdRN3fBdHyA7B3uxr7m17hMAUKd5UOhfyG6SxK6hqJso0VC31mRrEuBoNlVFtfghfDz20N6AZMrt_lJSklvLa9G-sbkUXDCLtsxcb4-GLH1FE2Y7gljSfaGjMd_4zU3MKN-TMqfdJd7Ctn-IpxWFQA0qHeT7KkrJW0Gd2qMt3sbgxJhbvheP-AXbOL6_yuJ7lobsb7dUYOgs9STxvKmEcxlTc-ckBsJqU31BpQlFOpgcHLNvNbjVYMOne0WSiQ8FumSTkSibZ13_Do.v4lCQDQf-1QeaqdPiGTRmnOitw77meOSLmWaPEotIyY&dib_tag=se&keywords=nail+polish&qid=1733849894&s=beauty&sr=1-5"

session6 <- bow(product6_url,
               user_agent = "Educational")
session6
```

```{r}
library(rvest)

product_6 <- scrape(session6)

reviewer <-  product_6 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_6 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_6 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_6 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_6 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_6 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product6df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product6df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product7_url <- "https://www.amazon.com/Beetles-Color-Gel-Nail-Polish/dp/B0CGZBNB24/ref=sr_1_6?dib=eyJ2IjoiMSJ9.Ay87Sh-z2Ng0pSHB2I3WeDa8bxbVpUdRN3fBdHyA7B3uxr7m17hMAUKd5UOhfyG6SxK6hqJso0VC31mRrEuBoNlVFtfghfDz20N6AZMrt_lJSklvLa9G-sbkUXDCLtsxcb4-GLH1FE2Y7gljSfaGjMd_4zU3MKN-TMqfdJd7Ctn-IpxWFQA0qHeT7KkrJW0Gd2qMt3sbgxJhbvheP-AXbOL6_yuJ7lobsb7dUYOgs9STxvKmEcxlTc-ckBsJqU31BpQlFOpgcHLNvNbjVYMOne0WSiQ8FumSTkSibZ13_Do.v4lCQDQf-1QeaqdPiGTRmnOitw77meOSLmWaPEotIyY&dib_tag=se&keywords=nail+polish&qid=1733849894&s=beauty&sr=1-6"
	
session7 <- bow(product7_url,
               user_agent = "Educational")
session7
```

```{r}
library(rvest)

product_7 <- scrape(session7)

reviewer <-  product_7%>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_7 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_7 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_7 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_7 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_7 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 

Product7df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product7df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product8_url <- "https://www.amazon.com/modelones-Natural-Concealer-Foundation-Imperfection/dp/B0CNR8RMXT/ref=sr_1_13_sspa?dib=eyJ2IjoiMSJ9.Ay87Sh-z2Ng0pSHB2I3WeDa8bxbVpUdRN3fBdHyA7B3uxr7m17hMAUKd5UOhfyG6SxK6hqJso0VC31mRrEuBoNlVFtfghfDz20N6AZMrt_lJSklvLa9G-sbkUXDCLtsxcb4-GLH1FE2Y7gljSfaGjMd_4zU3MKN-TMqfdJd7Ctn-IpxWFQA0qHeT7KkrJW0Gd2qMt3sbgxJhbvheP-AXbOL6_yuJ7lobsb7dUYOgs9STxvKmEcxlTc-ckBsJqU31BpQlFOpgcHLNvNbjVYMOne0WSiQ8FumSTkSibZ13_Do.v4lCQDQf-1QeaqdPiGTRmnOitw77meOSLmWaPEotIyY&dib_tag=se&keywords=nail+polish&qid=1733849894&s=beauty&sr=1-13-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1"

session8 <- bow(product8_url,
               user_agent = "Educational")
session8
```

```{r}
library(rvest)

product_8 <- scrape(session8)

reviewer <-  product_8 %>%
html_nodes('.a-profile-name') %>%
    html_text()
 
dates <- product_8 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_8 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_8 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_8 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_8 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product8df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product8df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product9_url <- "https://www.amazon.com/AZUREBEAUTY-Glitter-Natural-Infinite-Salon-Quality/dp/B0D9VZ9CH1/ref=sr_1_19_sspa?dib=eyJ2IjoiMSJ9.Ay87Sh-z2Ng0pSHB2I3WeDa8bxbVpUdRN3fBdHyA7B3uxr7m17hMAUKd5UOhfyG6SxK6hqJso0VC31mRrEuBoNlVFtfghfDz20N6AZMrt_lJSklvLa9G-sbkUXDCLtsxcb4-GLH1FE2Y7gljSfaGjMd_4zU3MKN-TMqfdJd7Ctn-IpxWFQA0qHeT7KkrJW0Gd2qMt3sbgxJhbvheP-AXbOL6_yuJ7lobsb7dUYOgs9STxvKmEcxlTc-ckBsJqU31BpQlFOpgcHLNvNbjVYMOne0WSiQ8FumSTkSibZ13_Do.v4lCQDQf-1QeaqdPiGTRmnOitw77meOSLmWaPEotIyY&dib_tag=se&keywords=nail+polish&qid=1733849894&s=beauty&sr=1-19-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1"

session9 <- bow(product9_url,
               user_agent = "Educational")
session9
```

```{r}
library(rvest)

product_9 <- scrape(session9)

reviewer <-  product_9 %>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_9 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_9 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_9 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_9 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_9 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product9df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product9df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product10_url <- "https://www.amazon.com/FlexiNail-Penetrating-Fingernail-Conditioner-Strengthener/dp/B0CSF22383/ref=sr_1_22_sspa?dib=eyJ2IjoiMSJ9.Ay87Sh-z2Ng0pSHB2I3WeDa8bxbVpUdRN3fBdHyA7B3uxr7m17hMAUKd5UOhfyG6SxK6hqJso0VC31mRrEuBoNlVFtfghfDz20N6AZMrt_lJSklvLa9G-sbkUXDCLtsxcb4-GLH1FE2Y7gljSfaGjMd_4zU3MKN-TMqfdJd7Ctn-IpxWFQA0qHeT7KkrJW0Gd2qMt3sbgxJhbvheP-AXbOL6_yuJ7lobsb7dUYOgs9STxvKmEcxlTc-ckBsJqU31BpQlFOpgcHLNvNbjVYMOne0WSiQ8FumSTkSibZ13_Do.v4lCQDQf-1QeaqdPiGTRmnOitw77meOSLmWaPEotIyY&dib_tag=se&keywords=nail+polish&qid=1733849894&s=beauty&sr=1-22-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1"
	
session10 <- bow(product10_url,
               user_agent = "Educational")
session10
```

```{r}
library(rvest)

product_10 <- scrape(session10)

reviewer <-  product_10 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_10 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_10 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_10 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_10 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_10 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 

Product10df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product10df
```

e.  Haircare_url

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product1_url <- "https://www.amazon.com/Kitsch-Recycled-Plastic-Accessories-Little/dp/B09GYPGLZZ/ref=sr_1_1_sspa?c=ts&dib=eyJ2IjoiMSJ9.4q2Z7pwNO1jMkrBtK_H1gy_YfJ65OcHhoUCvjp8L8F_GLoTubrAZzhiy1sHr5Smyj1uXcZcgb2OGmjdGwhs4utoAhq5qp-iZ6MGLzz9s2aU0jdLrSzHsbiRfT6_WEREIdwkP6M8O-w2WaSUAT4n01K-3M8IerFPa_jxNlIXxI3nYCmvkRm-eV44i0_HiJCGKB1XouxmY11ihBUCsL1--zS2MZFbn4BucIvJklv8c85cYm1L8mrSvFKeeW5s6qTC4593weyMYSQto3Hlv1eYL8yy_UtoJrg4YpwdMenvPIOE.v3YA6IA87Hb5wRd8Me2TcUS7dtZZa3D46v6p1Yi-Xn8&dib_tag=se&keywords=Hair+Styling+Accessories&qid=1733850546&s=beauty&sr=1-1-spons&ts_id=11057971&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1"

session1 <- bow(product1_url,
               user_agent = "Educational")
session1
```

```{r}
library(rvest)

product_1 <- scrape(session1)

reviewer <-  product_1%>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_1 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_1 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
  
 review_titles <- product_1 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_1%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_1 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product1df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product1df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product2_url <- "https://www.amazon.com/Microfiber-Hicober-Turbans-Drying-Towels/dp/B08S31RWBK/ref=sr_1_4?c=ts&dib=eyJ2IjoiMSJ9.4q2Z7pwNO1jMkrBtK_H1gy_YfJ65OcHhoUCvjp8L8F_GLoTubrAZzhiy1sHr5Smyj1uXcZcgb2OGmjdGwhs4utoAhq5qp-iZ6MGLzz9s2aU0jdLrSzHsbiRfT6_WEREIdwkP6M8O-w2WaSUAT4n01K-3M8IerFPa_jxNlIXxI3nYCmvkRm-eV44i0_HiJCGKB1XouxmY11ihBUCsL1--zS2MZFbn4BucIvJklv8c85cYm1L8mrSvFKeeW5s6qTC4593weyMYSQto3Hlv1eYL8yy_UtoJrg4YpwdMenvPIOE.v3YA6IA87Hb5wRd8Me2TcUS7dtZZa3D46v6p1Yi-Xn8&dib_tag=se&keywords=Hair+Styling+Accessories&qid=1733850546&s=beauty&sr=1-4&ts_id=11057971"

session2 <- bow(product2_url,
               user_agent = "Educational")
session2
```

```{r}
library(rvest)

product_2 <- scrape(session2)

reviewer <-  product_2 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_2 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_2 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_2 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_2%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_2 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product2df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product2df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product3_url <- "https://www.amazon.com/Goody-Accessories-Everyday-Essentials-Women/dp/B0DG94SZT4/ref=sr_1_5?c=ts&dib=eyJ2IjoiMSJ9.4q2Z7pwNO1jMkrBtK_H1gy_YfJ65OcHhoUCvjp8L8F_GLoTubrAZzhiy1sHr5Smyj1uXcZcgb2OGmjdGwhs4utoAhq5qp-iZ6MGLzz9s2aU0jdLrSzHsbiRfT6_WEREIdwkP6M8O-w2WaSUAT4n01K-3M8IerFPa_jxNlIXxI3nYCmvkRm-eV44i0_HiJCGKB1XouxmY11ihBUCsL1--zS2MZFbn4BucIvJklv8c85cYm1L8mrSvFKeeW5s6qTC4593weyMYSQto3Hlv1eYL8yy_UtoJrg4YpwdMenvPIOE.v3YA6IA87Hb5wRd8Me2TcUS7dtZZa3D46v6p1Yi-Xn8&dib_tag=se&keywords=Hair+Styling+Accessories&qid=1733850546&s=beauty&sr=1-5&ts_id=11057971"

session3 <- bow(product3_url,
               user_agent = "Educational")
session3
```

```{r}
library(rvest)

product_3 <- scrape(session3)

reviewer <-  product_3 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_3 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_3 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
review_titles <- product_3 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_3%>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_3 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product3df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product3df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product4_url <- "https://www.amazon.com/Kitsch-Metal-French-Hair-Women/dp/B0CRZRM3LP/ref=sr_1_6?c=ts&dib=eyJ2IjoiMSJ9.4q2Z7pwNO1jMkrBtK_H1gy_YfJ65OcHhoUCvjp8L8F_GLoTubrAZzhiy1sHr5Smyj1uXcZcgb2OGmjdGwhs4utoAhq5qp-iZ6MGLzz9s2aU0jdLrSzHsbiRfT6_WEREIdwkP6M8O-w2WaSUAT4n01K-3M8IerFPa_jxNlIXxI3nYCmvkRm-eV44i0_HiJCGKB1XouxmY11ihBUCsL1--zS2MZFbn4BucIvJklv8c85cYm1L8mrSvFKeeW5s6qTC4593weyMYSQto3Hlv1eYL8yy_UtoJrg4YpwdMenvPIOE.v3YA6IA87Hb5wRd8Me2TcUS7dtZZa3D46v6p1Yi-Xn8&dib_tag=se&keywords=Hair+Styling+Accessories&qid=1733850546&s=beauty&sr=1-6&ts_id=11057971"

session4 <- bow(product4_url,
               user_agent = "Educational")
session4
```

```{r}
library(rvest)

product_4 <- scrape(session4)

reviewer <-  product_4 %>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_4 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_4 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_4 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)


text_review <- product_4 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_4 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product4df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product4df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product5_url <- "https://www.amazon.com/Teenitor-Elastic-Colorful-Elatic-Accessories/dp/B0C4KW8H77/ref=sr_1_9?c=ts&dib=eyJ2IjoiMSJ9.4q2Z7pwNO1jMkrBtK_H1gy_YfJ65OcHhoUCvjp8L8F_GLoTubrAZzhiy1sHr5Smyj1uXcZcgb2OGmjdGwhs4utoAhq5qp-iZ6MGLzz9s2aU0jdLrSzHsbiRfT6_WEREIdwkP6M8O-w2WaSUAT4n01K-3M8IerFPa_jxNlIXxI3nYCmvkRm-eV44i0_HiJCGKB1XouxmY11ihBUCsL1--zS2MZFbn4BucIvJklv8c85cYm1L8mrSvFKeeW5s6qTC4593weyMYSQto3Hlv1eYL8yy_UtoJrg4YpwdMenvPIOE.v3YA6IA87Hb5wRd8Me2TcUS7dtZZa3D46v6p1Yi-Xn8&dib_tag=se&keywords=Hair+Styling+Accessories&qid=1733850546&s=beauty&sr=1-9&ts_id=11057971"

session5 <- bow(product4_url,
               user_agent = "Educational")
session5
```

```{r}
library(rvest)

product_5 <- scrape(session5)

reviewer <-  product_5%>%
html_nodes('.a-profile-name') %>%
    html_text()
 
dates <- product_5 %>%
    html_nodes('.review-date') %>%
    html_text()
  
 review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_5 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_5 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_5 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_5 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text() 

Product5df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product5df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product6_url <- "https://www.amazon.com/Kitsch-Scrunchies-Womens-Hair-Eucalyptus/dp/B0BJS1NVKM/ref=sr_1_7?c=ts&dib=eyJ2IjoiMSJ9.4q2Z7pwNO1jMkrBtK_H1gy_YfJ65OcHhoUCvjp8L8F_GLoTubrAZzhiy1sHr5Smyj1uXcZcgb2OGmjdGwhs4utoAhq5qp-iZ6MGLzz9s2aU0jdLrSzHsbiRfT6_WEREIdwkP6M8O-w2WaSUAT4n01K-3M8IerFPa_jxNlIXxI3nYCmvkRm-eV44i0_HiJCGKB1XouxmY11ihBUCsL1--zS2MZFbn4BucIvJklv8c85cYm1L8mrSvFKeeW5s6qTC4593weyMYSQto3Hlv1eYL8yy_UtoJrg4YpwdMenvPIOE.v3YA6IA87Hb5wRd8Me2TcUS7dtZZa3D46v6p1Yi-Xn8&dib_tag=se&keywords=Hair+Styling+Accessories&qid=1733850546&s=beauty&sr=1-7&ts_id=11057971"

session6 <- bow(product6_url,
               user_agent = "Educational")
session6
```

```{r}
library(rvest)

product_6 <- scrape(session6)

reviewer <-  product_6 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_6 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_6 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_6 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_6 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_6 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product6df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product6df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product7_url <- "https://www.amazon.com/Kitsch-Elastic-Hair-Ties-Women/dp/B08H6V3Q5Y/ref=sr_1_8?c=ts&dib=eyJ2IjoiMSJ9.4q2Z7pwNO1jMkrBtK_H1gy_YfJ65OcHhoUCvjp8L8F_GLoTubrAZzhiy1sHr5Smyj1uXcZcgb2OGmjdGwhs4utoAhq5qp-iZ6MGLzz9s2aU0jdLrSzHsbiRfT6_WEREIdwkP6M8O-w2WaSUAT4n01K-3M8IerFPa_jxNlIXxI3nYCmvkRm-eV44i0_HiJCGKB1XouxmY11ihBUCsL1--zS2MZFbn4BucIvJklv8c85cYm1L8mrSvFKeeW5s6qTC4593weyMYSQto3Hlv1eYL8yy_UtoJrg4YpwdMenvPIOE.v3YA6IA87Hb5wRd8Me2TcUS7dtZZa3D46v6p1Yi-Xn8&dib_tag=se&keywords=Hair+Styling+Accessories&qid=1733850546&s=beauty&sr=1-8&ts_id=11057971"

session7 <- bow(product7_url,
               user_agent = "Educational")
session7
```

```{r}
library(rvest)

product_7 <- scrape(session7)

reviewer <-  product_7%>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_7 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_7 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_7 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_7 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_7 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product7df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product7df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product8_url <- "https://www.amazon.com/Winkeyes-Accessories-Modelling-Hairdresser-Braiding/dp/B07TN625SM/ref=sr_1_10?c=ts&dib=eyJ2IjoiMSJ9.4q2Z7pwNO1jMkrBtK_H1gy_YfJ65OcHhoUCvjp8L8F_GLoTubrAZzhiy1sHr5Smyj1uXcZcgb2OGmjdGwhs4utoAhq5qp-iZ6MGLzz9s2aU0jdLrSzHsbiRfT6_WEREIdwkP6M8O-w2WaSUAT4n01K-3M8IerFPa_jxNlIXxI3nYCmvkRm-eV44i0_HiJCGKB1XouxmY11ihBUCsL1--zS2MZFbn4BucIvJklv8c85cYm1L8mrSvFKeeW5s6qTC4593weyMYSQto3Hlv1eYL8yy_UtoJrg4YpwdMenvPIOE.v3YA6IA87Hb5wRd8Me2TcUS7dtZZa3D46v6p1Yi-Xn8&dib_tag=se&keywords=Hair+Styling+Accessories&qid=1733850546&s=beauty&sr=1-10&ts_id=11057971"

session8 <- bow(product8_url,
               user_agent = "Educational")
session8
```

```{r}
library(rvest)

product_8 <- scrape(session8)

reviewer <-  product_8 %>%
html_nodes('.a-profile-name') %>%
    html_text()
 
dates <- product_8 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_8 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_8 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_8 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_8 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product8df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product8df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product9_url <- "https://www.amazon.com/Wugbc-Accessories-Ponytail-Geometric-Non-Damage/dp/B0DGFN5J4M/ref=sr_1_11_sspa?c=ts&dib=eyJ2IjoiMSJ9.4q2Z7pwNO1jMkrBtK_H1gy_YfJ65OcHhoUCvjp8L8F_GLoTubrAZzhiy1sHr5Smyj1uXcZcgb2OGmjdGwhs4utoAhq5qp-iZ6MGLzz9s2aU0jdLrSzHsbiRfT6_WEREIdwkP6M8O-w2WaSUAT4n01K-3M8IerFPa_jxNlIXxI3nYCmvkRm-eV44i0_HiJCGKB1XouxmY11ihBUCsL1--zS2MZFbn4BucIvJklv8c85cYm1L8mrSvFKeeW5s6qTC4593weyMYSQto3Hlv1eYL8yy_UtoJrg4YpwdMenvPIOE.v3YA6IA87Hb5wRd8Me2TcUS7dtZZa3D46v6p1Yi-Xn8&dib_tag=se&keywords=Hair+Styling+Accessories&qid=1733850546&s=beauty&sr=1-11-spons&ts_id=11057971&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1"

session9 <- bow(product9_url,
               user_agent = "Educational")
session9
```

```{r}
library(rvest)

product_9 <- scrape(session9)

reviewer <-  product_9 %>%
html_nodes('.a-profile-name') %>%
    html_text()
  
dates <- product_9 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)

rating <- product_9 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

 review_titles <- product_9 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_9 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_9 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product9df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product9df
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

product10_url <- "https://www.amazon.com/Parcce-Nonslip-Perfect-Accessories-Christmas/dp/B0BJ31SN1Q/ref=sr_1_2_sspa?c=ts&dib=eyJ2IjoiMSJ9.4q2Z7pwNO1jMkrBtK_H1gy_YfJ65OcHhoUCvjp8L8F_GLoTubrAZzhiy1sHr5Smyj1uXcZcgb2OGmjdGwhs4utoAhq5qp-iZ6MGLzz9s2aU0jdLrSzHsbiRfT6_WEREIdwkP6M8O-w2WaSUAT4n01K-3M8IerFPa_jxNlIXxI3nYCmvkRm-eV44i0_HiJCGKB1XouxmY11ihBUCsL1--zS2MZFbn4BucIvJklv8c85cYm1L8mrSvFKeeW5s6qTC4593weyMYSQto3Hlv1eYL8yy_UtoJrg4YpwdMenvPIOE.v3YA6IA87Hb5wRd8Me2TcUS7dtZZa3D46v6p1Yi-Xn8&dib_tag=se&keywords=Hair+Styling+Accessories&qid=1733850546&s=beauty&sr=1-2-spons&ts_id=11057971&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1"

session10 <- bow(product10_url,
               user_agent = "Educational")
session10
```

```{r}
library(rvest)

product_10 <- scrape(session10)

reviewer <-  product_10 %>%
html_nodes('.a-profile-name') %>%
    html_text()

dates <- product_10 %>%
    html_nodes('.review-date') %>%
    html_text()
  
  review_dates <- gsub("Reviewed in .*? on\\s*", "", dates)
  
rating <- product_10 %>%
  html_nodes('.a-icon.a-icon-star.a-star-5.review-rating') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)
    
 review_titles <- product_10 %>%
    html_nodes('.review-title') %>%
    html_text()
  review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

text_review <- product_10 %>%
html_nodes('.a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content') %>%
    html_text() %>%
    trimws()

verified_purchase <- product_10 %>%
html_nodes('.a-size-mini.a-color-state.a-text-bold') %>%
    html_text()
```

```{r}
Product10df <- data.frame(
Reviewers = reviewer[1:20], 
Review_Date = review_dates[1:20],
Ratings = rating[1:20], 
Review_Titles = review_titles_clean[1:20],
Text_Reviews = text_review[1:20],
Verified_Puchase = verified_purchase[1:20],
stringsAsFactors = FALSE)

Product10df
```